version: '3'

services:

  app:
    image: anstane/leadhit_app

    ports:
      - "5000:5000"

    environment:
      FLASK_APP: app/app.py
      FLASK_RUN_HOST: 0.0.0.0

    command: ["sh", "-c", "poetry run pytest -v & poetry run flask run --host 0.0.0.0"]
